### ISSUE TITLE
will this simultaneously work at ios and android?

### ISSUE THREAD

**Issue by neo125874** [pushy-me/pushy-react-native#1]
as title,
on the official site , it only provides the android version react-native document, 

so,  how about the ios version?

**Comment by pushy-me** [comment]
Hi @neo125874,
Thanks for your inquiry.

At this time our React Native SDK only supports Android, however, we definitely have plans to support iOS as well.

We'll let you know once that's ready.

**Comment by pushy-me** [comment]
Hi @neo125874,
Great news, our engineers have finished working on iOS support for React Native!

To get started, refer to our detailed documentation: 
https://pushy.me/docs/additional-platforms/react-native
