### ISSUE TITLE
How to implement deep link with pushy

### ISSUE THREAD

**Issue by devfans** [pushy-me/pushy-react-native#11]
- Where to specify the link for the notification which will be triggered when the user clicks on the notification

- After users clicked the notification, then the link will be handled in App native ways?

- I see on the client side, there is a method as `Pushy.notify()` , so it will be called before emitting the notification, right? Is it possible to set the deep link here? 

The purpose of the questions is for finding the way to achieve cases like: client received a notification about new comments on his article. When the user clicks the notification from home screen, he shall be navigated to article tab in the App automatically.

**Comment by pushy-me** [comment]
Hi @devfans,
We'd be glad to explain.

Is this for an Android or iOS app (or both)?

**Comment by devfans** [comment]
Hello, 
It’s for both, using react-native. 
Thank you!

**Comment by pushy-me** [comment]
Hi @devfans,
For iOS, your `Pushy.setNotificationListener()` callback will be invoked when the user slides on your notification. You can then extract data from the payload via the `data` parameter of your `Pushy.setNotificationListener()`:

```
let action = data.action; // number
```

For Android, you will need to use another method other than `Pushy.listen()` if you want to customize the click behavior and handle it differently. 

We recommend using `react-native-push-notification` (just the local notification aspect of it):
https://github.com/zo0r/react-native-push-notification#local-notifications

This will allow you to further customize the notification click handling for Android.

**Comment by robert589** [comment]
can u give a more detailed example on how to handle user click on pushy push notification? 

From my code, setnotificationlistener has already been called before the user clicks it

**Comment by pushy-me** [comment]
Hi @robert589,
On Android, the notification listener callback is the one that actually issues and displays the notification by calling `Pushy.notify()`.

On iOS, the notification is already displayed by the system, and your notification listener callback is invoked when the user swipes and interacts with the notification. At that point, calling `Pushy.notify()` doesn't emit a system notification, but displays an in-app alert dialog instead.

For which platform do you want to handle the notification click differently?

**Comment by robert589** [comment]
I need to handle the click different for both.

For android, should I use react-native-push-notification#localNotifications?

**Comment by pushy-me** [comment]
Hi @robert589,
For Android, to handle the notification click event, indeed you should use the [`react-native-push-notification`](https://github.com/zo0r/react-native-push-notification) plugin's [`localNotification`](https://github.com/zo0r/react-native-push-notification#local-notifications) method to emit the notification, and the `onNotification` listener to listen for the notification click event:
PushNotification.configure({
  onNotification: function(notification) {
    console.log('NOTIFICATION:', notification);

    // process the notification

    // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  }
});
```

**Comment by pushy-me** [comment]
@robert589 Great news! We have just finished integrating this functionality into our React Native SDK.

Call the `Pushy.setNotificationClickListener((data) => {})` method from your application to listen for when the user clicks your notifications:

```
// Listen for push notifications clicked
Pushy.setNotificationClickListener(function (data) {
    // Display basic alert
    alert('Clicked notification: ' + data.message);

    // Navigate the user to another page or 
    // execute other logic on notification click
});
```

This is supported on both Android and iOS. Inside this method, you can then check the notification payload which was clicked and direct the user to the relevant page in your RN app.

To be able to access this method, please update our Pushy RN SDK by running the following commands in the root of your RN project:

```
npx react-native unlink pushy-react-native
npm install pushy-react-native@1.0.11 --save

npx react-native link pushy-react-native
```

Next, update the versions imported in your Android app's `build.gradle`:

```
// Pushy SDK for Android
compile 'me.pushy:sdk:1.0.53'

// Pushy SDK for React Native Android
compile 'me.pushy:sdk-react-native:1.0.12'
```

Also, modify your `Pushy.notify()` invocation in `App.js` to include a third parameter:
```
Pushy.notify(notificationTitle, notificationText, data);
```

Please let us know if you face any issues.
