### ISSUE TITLE
PushyModule.h Not Found

### ISSUE THREAD

**Issue by LoganArnett** [pushy-me/pushy-react-native#13]
I have followed the directions 3 different times and I get this error every time after linking the iOS project. 

![image](https://user-images.githubusercontent.com/8780547/54639405-a6132100-4a63-11e9-95a2-5c4eb59bd4f0.png)

Not sure if there is a better manual way to include this

**Comment by pushy-me** [comment]
Hi @LoganArnett,
I'd be glad to help.

It appears that the integration process of our RN iOS SDK did not go so smoothly.

1) Did you link the library?

```
react-native link pushy-react-native
```

2) Did you create an empty `.swift` file in your main RN Objective C project?

**Comment by pushy-me** [comment]
Closing due to lack of response. Please feel free to let us know if you are still facing this issue.

**Comment by anttivuor** [comment]
Hey,

I have the same error. I have linked the (react-native link react-native-pushy) successfully but I am not sure if I have added the blank .swift file correctly. Could you provide some more information about creating that? I think the documentation in pushy's website is kinda unclear.

Thanks!
