### ISSUE TITLE
Proper Cocoapods support

### ISSUE THREAD

**Issue by rizwankce** [pushy-me/pushy-react-native#16]
I'm trying to use the `pushy-react-native` to my existing native project (brown field). Since We use cocoapods as dependency manager and as I can see pushy also have a `podspec` file, thought it will be a easy integration. But I end up having some issues. The experience was not as easy as other popular react native community projects. 

To make it even better support for cocoapods. I would like to propose the below changes.

- Move the `PushyRN.podspec` to root directory 
- Mention correct version string (Probably someone has to update manually every time there is a new release Or we could automate it by getting version string from `package.json`)
- Mention correct source file link for `s.source_files`

By above changes it will be easy for brown field app developer to integrate the SDK.(also, if you watch React Native team plan closely - lean core - one of the action item was to support cocoapods to link IOS libraries, So we would be ready before it happens)

Happy to send PR!

**Comment by rizwankce** [comment]
To make a note, it won't break the existing functionalities. a.k.a with `react-native link ***`

**Comment by pushy-me** [comment]
Hi @rizwankce,
Thanks so much for these suggestions! 

It would be great if we could support native Cocoapods as well without relying on npm/RN link.

A PR for these would be greatly appreciated, as long as it doesn't break the current `npm install` and `react-native link` install procedure [in our docs](https://pushy.me/docs/additional-platforms/react-native).

Cheers! 🎉

**Comment by rizwankce** [comment]
@pushy-me Let me work on the PR and probably create a sample projects just to make sure it won't break existing functionalities.
