### ISSUE TITLE
iOS build error: PushyModule.h Not Found

### ISSUE THREAD

**Issue by anttivuor** [pushy-me/pushy-react-native#19]
Hey,

I am trying to implement Pushy in my React Native application. Android works fine but I cannot get iOS build to work. I always get error "'PushyModule.h' file not found" in Xcode (see screenshot).

![Screenshot 2019-05-16 at 11 49 50](https://user-images.githubusercontent.com/26520926/57840335-1a9edd80-77d1-11e9-8592-9e879ea15359.png)

I have run "react-native link pushy-react-native" successfully without any errors. Probably my mistake is in installation part "Add blank swift file". That seems pretty unclear for me. Could you provide more instructions for that part?

**Comment by pushy-me** [comment]
Hi @anttivuor,
We'd be glad to help.

1)  Open your React Native iOS app in Xcode by running the following command in your React Native project root:

```
open ios/*.xc*
```

2) In the file explorer (left panel), right click your project folder and select **New File...**.

3) Select **Swift File** and name it **Pushy.swift**.

4) When prompted, you may decline the creation of a bridging header for your project.

Please let us know if you encounter any further issues.

**Comment by dmydry** [comment]
Hi guys! I have the same issue. 

@pushy-me followed all instructions from your docs but can't import the PushyModule in Xcode

```'PushyModule.h' file not found```

Maybe there is just a problem with Header Search Paths, but I can't figure out how to fix it.
Any help will be appreciated

**Comment by pushy-me** [comment]
HI @dmydry,
Were you able to create a blank Swift file using the instructions above? Also, were you able to run `react-native link pushy-react-native` successfully?

**Comment by anttivuor** [comment]
Hello,

I am still having the same error. I tried adding the empty Pushy.swift file but that didn't fix the problem. Do you have some kind of example project? I think that would help since I could see how the installation has been done.

In case you these information.
I am using:
XCode 10.1 (10B61)
MacOS Mojave 10.14
React Native 58.6
pushy-react-native 1.0.8

**Comment by dmydry** [comment]
Hello @pushy-me 
Yes, I had no problem with all the steps provided in the instructions including a blank swift file and `react-native link pushy-react-native` command.

In my case I have an ejected expo project, sometimes it matters but for most of libraries it works as expected.

Anyway, as @anttivuor asked, a sample project would be a nice start to investigate.

**Comment by pushy-me** [comment]
Hi @dmydry,
This original issue by @anttivuor relates to a pure React Native project, please refer to our response regarding Expo / ExpoKit projects:
https://github.com/pushy-me/pushy-react-native/issues/20#issuecomment-497177504

**Comment by pushy-me** [comment]
Hi @anttivuor,
We have started preparing a React Native demo project and let you know once it's ready.

**Comment by pushy-me** [comment]
Hi @anttivuor,
In addition, please let us know if running the `react-native link pushy-react-native` command on your project directory returned the following output:

```
info Linking "pushy-react-native" iOS dependency
info iOS module "pushy-react-native" has been successfully linked
```

**Comment by pushy-me** [comment]
HI @anttivuor,
We have just published a sample project which integrates the Pushy SDK for React Native into a new React Native app:
https://github.com/pushy-me/pushy-demo-react-native

**Comment by anttivuor** [comment]
Finally got the app to compile. I replaced "#import <PushyModule.h>" with "#import './../../node_modules/pushy-react-native/ios/PushyModule.h'" to get that working

**Comment by pushy-me** [comment]
Thanks so much for letting us know how you managed to solve it @anttivuor. It's quite strange you had to use this import statement but if it works then perfect. 👍

**Comment by rajazz** [comment]
Hi, any pushy imported Objective C project sample available. I'm not able to add header to my project. Pushy module not found it says

**Comment by pushy-me** [comment]
Hi @rajazz,
Please make sure to add a blank Swift file (as mentioned in https://github.com/pushy-me/pushy-react-native/issues/19#issuecomment-493658935).

Also, please check whether `use_frameworks!` is uncommented in your `ios/Podfile`.
