### ISSUE TITLE
pushy native module not loaded,

### ISSUE THREAD

**Issue by amrshakya** [pushy-me/pushy-react-native#2]
i've have already hit the "react-native link pushy-react-native" and it is working fine on android but on ios it shows the "Pushy native module not loaded please make sure to run "react-native link pushy-react-native""

**Comment by pushy-me** [comment]
Hi @amrshakya,
1) Did you follow the instructions at https://pushy.me/docs/additional-platforms/react-native?
2) Open your project in Xcode:

```
open ios/*.xc*
```

3) Clean the project
4) Rebuild the project
5) Run the project from Xcode on your iOS device

Does it still throw this error?

**Comment by amrshakya** [comment]
Yes i did follow all the instruction as mentioned in the documentation.

**Comment by amrshakya** [comment]
it finally worked but now i get this but only on iOS.
![screen shot 2018-09-16 at 10 36 13 am](https://user-images.githubusercontent.com/16429984/45593031-78f29280-b99c-11e8-8040-888ae9a2c4a5.png)

**Comment by amrshakya** [comment]
it finally worked. but now i got these following warning only on iOS.
1. Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
2. Possible Unhandled Promise Rejection (id: 0): Error: Registration failed. Error Domain=NSCocoaErrorDomain Code =3010 "remote notifications are not supported in the simulator"

**Comment by pushy-me** [comment]
Hi @amrshakya,
1. If this is just a warning and the project compiles, please ignore it for now, as our plugin definitely has the `RCT_EXPORT_MODULE()` declaration: 
https://github.com/pushy-me/pushy-react-native/blob/d26870a3f855f6aa94224ece61c6ab1cee18d168/ios/PushyModule.m#L6


2. As the error states, unfortunately the iOS Simulator cannot register for nor receive notifications. To register for and receive push notifications from APNs using Pushy you actually need to be testing your app on a physical iOS device.

**Comment by amrshakya** [comment]
thanks.

**Comment by pushy-me** [comment]
Our pleasure. Please reach out with any further questions or issues.

**Comment by a396901990** [comment]
i only want using pushy for Android, get same error... can't get rid of it

**Comment by pushy-me** [comment]
Hi @a396901990,
Please reach out to our support e-mail at support@pushy.me with the full error message and we will be happy to provide further assistance.

**Comment by sohamad** [comment]
@a396901990 were u able to resolve this? i also want it for android only. I am getting the same error
