### ISSUE TITLE
What's the callback after click notification?

### ISSUE THREAD

**Issue by a396901990** [pushy-me/pushy-react-native#23]
What's the callback after click notification which generates by `pushy.notify()`, I can't find it in documentation

**Comment by pushy-me** [comment]
Hi @a396901990,
On iOS, we invoke the function you provide to `Pushy.setNotificationListener()` (in `App.js`) when the notification is interacted with (clicked/swiped). By default, the callback contains an invocation of `Pushy.notify()` which displays an alert dialog in-app. Feel free to modify this behavior. 

On Android, to listen for notification click, the `Pushy.notify()` implementation is basic and does not make it possible to handle notification click events.

To listen for click events, consider using a plugin called `react-native-push-notification` which makes it possible to emit local notifications and listen for click events:
https://github.com/zo0r/react-native-push-notification

You may ignore the remote notification aspects of this package and simply use the `PushNotification.localNotification()` method and the `onNotification()` callback function.

**Comment by pushy-me** [comment]
@a396901990 Great news! We have just finished integrating this functionality into our React Native SDK.

Call the `Pushy.setNotificationClickListener((data) => {})` method from your application to listen for when the user clicks your notifications:

```
// Listen for push notifications clicked
Pushy.setNotificationClickListener(function (data) {
    // Display basic alert
    alert('Clicked notification: ' + data.message);

    // Navigate the user to another page or 
    // execute other logic on notification click
});
```

This is supported on both Android and iOS. Inside this method, you can then check the notification payload which was clicked and direct the user to the relevant page in your RN app.

To be able to access this method, please update our Pushy RN SDK by running the following commands in the root of your RN project:

```
npx react-native unlink pushy-react-native
npm install pushy-react-native@1.0.11 --save

npx react-native link pushy-react-native
```

Next, update the versions imported in your Android app's `build.gradle`:

```
// Pushy SDK for Android
compile 'me.pushy:sdk:1.0.53'

// Pushy SDK for React Native Android
compile 'me.pushy:sdk-react-native:1.0.12'
```

Also, modify your` Pushy.notify()` invocation in `App.js` to include a third parameter:
```
Pushy.notify(notificationTitle, notificationText, data);
```

Please let us know if you face any issues.

**Comment by cchoici** [comment]
@pushy-me 
it is not workable when app is closed...., Pushy.setNotificationClickListener not trigger on Android, have any suggestion?

**Comment by cchoici** [comment]
OK~~it still need react-native-push-notifiaciton plugin used.

**Comment by pushy-me** [comment]
Hi @cchoici,
Did you get `Pushy.setNotificationClickListener()` to work after migrating back to using `Pushy.notify()` in your `Pushy.setNotificationListener()`?

**Comment by cchoici** [comment]
yes, i did it.
everythins was fine except   setNotificationClickListener  function not
triggger when app was closed.
* app opened is workable.
* app in recently apss is workable.
* app closed is not workable.
 i used galaxy tab s3

Pushy <notifications@github.com> 于 2019年12月27日周五 08:52写道：

**Comment by pushy-me** [comment]
Hi @cchoici,
Just to confirm -- is everything working now, including when app is closed (not in recent list)?

**Comment by cchoici** [comment]
Yes, I used the react-native-push-notification to listen click notification
event.
Thanks

Pushy <notifications@github.com> 于 2019年12月30日周一 09:42写道：
