### ISSUE TITLE
IOS Push Notification

### ISSUE THREAD

**Issue by robert589** [pushy-me/pushy-react-native#25]
Hi, My IOS device has been registered to pushy.me dashboard
And i have configured the APN, however, i did not receive any push notification in the phone.
I also did not get any pending notifications in the dashboard, why this happen?

**Comment by robert589** [comment]
I just figure out that ios dont receive notification in the foreground

**Comment by pushy-me** [comment]
Hi @robert589,
Indeed on iOS, the default behavior for in-app notifications is to invoke your Pushy notification listener which will create an alert dialog (by calling `Pushy.notify()`):

```
Pushy.setNotificationListener(async (data) => {
    // Print notification payload data
    console.log('Received notification: ' + JSON.stringify(data));

    // Notification title
    let notificationTitle = 'MyApp';

    // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
    let notificationText = data.message || 'Test notification';

    // Display basic system notification
    Pushy.notify(notificationTitle, notificationText);
});
```
