### ISSUE TITLE
'PushyRN/PushyRN-Swift.h' file not found

### ISSUE THREAD

**Issue by leethree** [pushy-me/pushy-react-native#29]
> node_modules/pushy-react-native/ios/PushyModule.m:2:9: 'PushyRN/PushyRN-Swift.h' file not found

I got this error in React Native 0.59. We are using manually linking for our iOS project and it no longer compiles.

**Comment by pushy-me** [comment]
Hi @leethree,
By manual linking, do you mean that you are using a `Podfile` instead of `npm` to install iOS dependencies for your RN app?

**Comment by leethree** [comment]
manual linking means we are not using Cocoapods. see https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

**Comment by pushy-me** [comment]
Hi @leethree,
Thanks for the additional information. We reproduced the error you're facing and have come up with a solution for manual linking.

Our RN SDK depends on Cocoapods to create an `Objective C Bridging Header` which it does automatically when `pod install` is run by `react-native link`.

To manually create and configure a Bridging Header, please follow these instructions:

1) In Xcode, right click `PushyRN.xcodeproj` (under Libraries) and click **New File...**
2) Select **Header File** and name it `PushyRN-Bridging-Header.h`.
3) Go to the project `Build Settings` for `PushyRN.xcodeproj` and search for `Bridging Header`
4) Set the value for `Objective C Bridging Header` to `PushyRN-Bridging-Header.h`:

![Screen Shot 2020-01-11 at 2 16 33 PM](https://user-images.githubusercontent.com/13287630/72196443-fa691080-347c-11ea-904b-63fd398745ee.png)

5) Edit `PushyModule.m`:

Find:
`#import <PushyRN/PushyRN-Swift.h>` 

Replace with:
`#import <PushyRN-Bridging-Header.h>`

6) Recompile the project 🎉 

Please let me know if this succeeds!

**Comment by leethree** [comment]
I added the bridging header but it still complains "Unknown type name 'Pushy'". 

Also even if it works, the changes will be overwritten by `yarn install`. 

I think it would be helpful to add a note to the documentation saying the current version is only compatible with RN > 0.60

**Comment by pushy-me** [comment]
Hi @leethree,
1) Please provide more insight on this new error -- can you please post a screenshot, or let us know which file and line number it is occurring on?

2) We could bake this into the project by adding a bridging header and specifying it in the project properties to facilitate manual linking and avoid losing changes by `yarn install`. Cocoapods would still likely work and generate its own bridging header.

3) What makes this plugin not compatible with RN <= `0.60`?

**Comment by leethree** [comment]
I think the problem is the import statement. I changed it to `#import "PushyRN-Swift.h"` and now it builds. Bridging-Header is not necessary.

Maybe worth trying to update the code like this:
```objc
#if __has_include(<PushyRN/PushyRN-Swift.h>)
#import <PushyRN/PushyRN-Swift.h>
#else
#import "PushyRN-Swift.h"
#endif
```

Before RN 0.60, Cocoapods is not used by default. So it's common to use manual linking for 3rd party libraries. And people will see this issue if they don't use Cocoapods.

**Comment by leethree** [comment]
I added a PR for this: #30

**Comment by pushy-me** [comment]
Awesome work @leethree, we've merged the PR 😄
