### ISSUE TITLE
Notification Click Listener not firing

### ISSUE THREAD

**Issue by bohrend** [pushy-me/pushy-react-native#31]
I am having trouble getting the push notification click listener to trigger, i have upgraded from pushy-react-native 1.0.10 to 1.0.14.

I have added the click listener in my App.js file, as per example react-native pushy app

`Pushy.setNotificationClickListener(async (data) => {
    console.log('pushy_click');
});`

However clicking on incoming notifications doesn't trigger event, have tried with app closed, and opened, have tried moving the Pushy.setNotificationClickListener to different places in app. 

any help would be appreciated

**Comment by pushy-me** [comment]
Hi @bohrend,
Where are you calling `Pushy.listen()` in your app?

Please make sure to invoke it first thing in your `App.js`'s `componentDidMount()` method. 

Also, are you by any chance using any other push notification library in your app such as FCM or OneSignal, or `zo0r/react-native-push-notification`?

**Comment by bohrend** [comment]
Hi thanks for the reply, yes i invoke listen() in App.js, I am not using any other push notification library, only pushy. I am testing this on the android emulator. The only thing I am doing differently compared to the react-native-pushy sample app, it uses 3 arguments when calling Pushy.notify(), however adding 3 arguments to Pushy.notify() gives error (3arguments given, only 2 expected) myside, but not sure if this will cause clicklistener to not fire

```
Pushy.setNotificationClickListener(async (data) => {
    console.log('pushy_click');
});

class App extends Component {
    componentDidMount(){
        Pushy.listen();
    }
```


` Pushy.notify(notificationTitle, notificationText);`

**Comment by pushy-me** [comment]
Hi @bohrend,
That would explain the issue. Indeed the third parameter is required for tracking notification clicks.

If you're getting an error when doing so, it's because you need to update the Pushy RN Android SDK version in build.gradle to `1.0.13`:
```
// Pushy SDK for Android
compile 'me.pushy:sdk:1.0.54'

// Pushy SDK for React Native Android
compile 'me.pushy:sdk-react-native:1.0.13'
```

**Comment by bohrend** [comment]
cool that seems to have fixed it, thanks!
