### ISSUE TITLE
Ios notification badge number not being reset when opening the app

### ISSUE THREAD

**Issue by bohrend** [pushy-me/pushy-react-native#35]
Hi, when does the badge number on the app icon reset, its a react native app, and opening the app from the push notification does not seem to reset the badge back to 0, is this something I must do manually?

thanks

**Comment by pushy-me** [comment]
Hi @bohrend,
Our Pushy SDK resets the badge number automatically when you call `Pushy.notify()` in your `Pushy.setNotificationListener((data) => {})` callback method of your App.js file, outside the `Component` class declaration:
https://github.com/pushy-me/pushy-react-native/blob/9720a284f5d3fbebf20860860eacbaf820b6581b/ios/PushyModule.m#L181-L182

Please ensure you place this code in `App.js` and make a call to `Pushy.notify()`.
```
// Please place this code in App.js,
// After the import statements, and before the Component class

Pushy.setNotificationListener(async (data) => {
    // Print notification payload data
    console.log('Received notification: ' + JSON.stringify(data));

    // Notification title
    let notificationTitle = 'MyApp';

    // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
    let notificationText = data.message || 'Test notification';

    // Display basic system notification
    Pushy.notify(notificationTitle, notificationText, data);
});
```

**Comment by bohrend** [comment]
ok thanks
