### ISSUE TITLE
react native notificationlistener not firing for ios

### ISSUE THREAD

**Issue by bohrend** [pushy-me/pushy-react-native#36]
notificationlistener is inside app.js, and it fires on android, however for ios it doesnt fire when app is either closed or in background and tapping on notification

```
Pushy.setNotificationListener(async (data) => {
    console.log('pushy')
    // Works on both Android and iOS
    Alert.alert(
        'Alert Title',
        'My Alert Msg',
    [
      {text: 'Ask me later', onPress: () => console.log('Ask me later pressed')},
      {text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
      {text: 'OK', onPress: () => console.log('OK Pressed')},
    ],
    { cancelable: false }
  )
```

**Comment by bohrend** [comment]
"pushy-react-native": "^1.0.14",

**Comment by pushy-me** [comment]
Hi @bohrend,
Please make sure to initialize the plugin by adding the following line to your `ios/app/AppDelegate.m` file, anywhere inside your app's `didFinishLaunchingWithOptions` method:

```
// Initialize Pushy Module
[PushyModule didFinishLaunchingWithOptions:launchOptions];
```

Make sure to add the required import statement as well:

```
#import <PushyModule.h>
```

You may close the Xcode project now.

**Comment by bohrend** [comment]
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // Initialize Pushy Module
  [PushyModule didFinishLaunchingWithOptions:launchOptions];
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"test"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}
```

Hi thanks for feedback, I have already added this, 

I have upgraded pushy for the android version a while back to support the pushy.notify() method (with 3 parameters, instead of 2, couldnt remember the versions) could this somehow cause the issue, do I need to update the ios version?

my podfile does not contain `use_frameworks!` anymore, however the pushy sdk is in my libraries file in my project.

**Comment by pushy-me** [comment]
Hi @bohrend,
That's most likely why -- please make sure to update the Pushy iOS SDK as well by re-linking:

```
react-native unlink pushy-react-native
react-native link pushy-react-native
cd ios && rm -rf Pods && pod install
```

Please let us know if it resolves the issue.

**Comment by bohrend** [comment]
Hi @pushy-me, thank you, however I now get the following:

cd ios && rm -rf Pods && pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "React":
  In Podfile:
    PushyRN (from `../node_modules/pushy-react-native`) was resolved to 1.0.14, which depends on
      React (< 1.0.0, >= 0.13.0)

None of your spec sources contain a spec satisfying the dependency: `React (< 1.0.0, >= 0.13.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by pushy-me** [comment]
HI @bohrend,
What version of `React` is your project using? Please paste your `Podfile`.

**Comment by bohrend** [comment]
podfile contents:
```
target 'appname' do
    use_frameworks!
# Add new pods below this line
pod 'PushyRN', :path => '../node_modules/pushy-react-native'
end
```

project package.json:
```

"pushy-react-native": "^1.0.14",
"react": "16.8.3",
"react-native": "0.59.9",
```

**Comment by pushy-me** [comment]
Try having React Native rebuild for iOS:
```
react-native run-ios
```

**Comment by bohrend** [comment]
Showing Recent Messages
:-1: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

and if i do pod install i get:

CocoaPods could not find compatible versions for pod "React":
  In Podfile:
    PushyRN (from `../node_modules/pushy-react-native`) was resolved to 1.0.14, which depends on
      React (< 1.0.0, >= 0.13.0)

**Comment by pushy-me** [comment]
Hi @bohrend,
I'm not sure why, but the Pushy RN SDK seems to have broken your RN project.

Let's try unlinking the Pushy RN library and running `pod install`:

```
react-native unlink pushy-react-native
cd ios && rm -rf Pods && pod install
```

>

**Comment by pushy-me** [comment]
Hi @bohrend,
I'm not sure why, but the Pushy RN SDK seems to have broken your RN project.

Let's try unlinking the Pushy RN library and running `pod install`:

```
react-native unlink pushy-react-native
cd ios && rm -rf Pods && pod install
```

**Comment by bohrend** [comment]
> Analyzing dependencies
> Downloading dependencies
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.
> 
> [!] The Podfile does not contain any dependencies.

**Comment by bohrend** [comment]
do you maybe have a slack channel we can discuss this?

**Comment by pushy-me** [comment]
I apologize, but at this time, we don't offer tech support via Slack.

Please try re-integrating our plugin:
https://pushy.me/docs/additional-platforms/react-native

Don't run `rm -rf Pods` or `pod install` manually, as that seems to be breaking your project. Let's let React Native handle the pod install.

**Comment by shaheer2020** [comment]
I am facing similar issue. The device is getting registered using the react native methods. However the

```
Pushy.setNotificationListener(async (data) => {
  // Print notification payload data
  console.log('Received notification: ' + JSON.stringify(data));
  
  // Notification title
  let notificationTitle = 'MyApp';
  
  // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
  let notificationText = data.message || 'Test notification';
  
  // Display basic system notification
  Pushy.notify(notificationTitle, notificationText, data);
  
  // Clear iOS badge count
  Pushy.setBadge && Pushy.setBadge(0);
});
```
method is not getting fired.

**Comment by pushy-me** [comment]
Hi @shaheer2020,
Please ensure you are not using any other React Native plugin which swizzles or depends on the following AppDelegate APNs methods:

1) `didReceiveRemoteNotification`
2) `didRegisterForRemoteNotificationsWithDeviceToken`
3) `didFailToRegisterForRemoteNotificationsWithError`

Plugins that may be swizzling these methods and thus interfering include:
1) Firebase (FCM and/or Firebase Auth)
2) Other push notification plugins such as OneSignal
