### ISSUE TITLE
Use with Proguard

### ISSUE THREAD

**Issue by paschaldev** [pushy-me/pushy-react-native#37]
Unable to register application with backend server. Could not get device token on release build only.

![Screenshot_20200307-210329](https://user-images.githubusercontent.com/13323281/76152254-a9ad1700-60bd-11ea-8f85-0839ecbf7a26.png)

**Comment by pushy-me** [comment]
Hi @paschaldev,
If you use ProGuard, make sure the following lines are present in your `proguard-rules.pro` file:

```
-dontwarn me.pushy.**
-keep class me.pushy.** { *; }
```

**Comment by paschaldev** [comment]
Thank you. Please update the documentation for new users.

**Comment by pushy-me** [comment]
Hi @paschaldev,
It is indeed mentioned :)
https://pushy.me/docs/android/get-sdk

**Comment by paschaldev** [comment]
Oh wow didn't notice that. Thank you
