### ISSUE TITLE
setNotificationClickListener navigate to another screen

### ISSUE THREAD

**Issue by jothikannan** [pushy-me/pushy-react-native#39]
I need to redirect the user another screen after the user click the notification, so I used setNotificationClickListener to detect the click, but when I use react-navigation actions to do it doesn't move to a specific screen, it always redirects to the same dashboard screen

```
Pushy.setNotificationClickListener(function (data) {
  // Display basic alert
  NavigationActions.navigate('Details');
  // Navigate the user to another page or 
  // execute other logic on notification click
});
 
```

**Comment by pushy-me** [comment]
Hi @jothikannan,
Apologies for our delayed response.

It seems like this issue may not be related to the Pushy RN SDK, as it is correctly invoking your callback which you passed into `Pushy.setNotificationClickListener()`. Please investigate [Navigation Actions](https://reactnavigation.org/docs/4.x/navigation-actions/) to understand why it keeps redirecting you to the same screen.
