### ISSUE TITLE
Unsubscribe from topic not working in react native

### ISSUE THREAD

**Issue by tarikchakur** [pushy-me/pushy-react-native#4]
Hi. It seems there is an unsubscribe method and the Pushy object, but there is no reference of it in the documentation concerning react-native.
I tried to unsubscribe a device from a topic it returns true in the resolved promise, but the device is still subscribed.

Is there a way to unsubscribe from topic in your API, if not will it be added in the future.
thanks in advance. great library btw.

**Comment by pushy-me** [comment]
Hi @tarikchakur,
Calling `Pushy.unsubscribe()` is definitely supported in our React Native SDK, syntax is as follows:

```
// Unsubscribe the device from a topic
Pushy.unsubscribe('news').then(() => {
  // Subscribe successful
  alert('Unsubscribed from topic successfully');
}).catch((err) => {
  // Handle errors
  console.error(err);
});
```

**Comment by tarikchakur** [comment]
@pushy-me It working well. Thanks. 
I was wondering if there is a way to specify the notification content in iOS, in the client side just like in Android we use `Pushy.notify( notificationTitle, notificationText );`  to specify the title and the message on `Pushy.setNotificationListener` event received.
From the documentation it seems that the notification content can only be set from the **Sender** but not from the **Receiver** in **iOS**.
