### ISSUE TITLE
How to receive push notification on when user logged in?

### ISSUE THREAD

**Issue by jothikannan** [pushy-me/pushy-react-native#40]
Is there any way to receive the push notification only when the users are logged in,  how to stop the notifications when the user logged out? what is the logic we need to use to get it done?

I tried` toggleNotifications(true) `when the user logged out, and `toggleNotifications(false) `when the user logged in, but unfortunately it ended up with the error attached like in the image

![image1](https://user-images.githubusercontent.com/4100047/76443618-bba5f700-63e8-11ea-844c-02d789c20c0c.png)

**Comment by pushy-me** [comment]
Hi @jothikannan,
`Pushy.toggleNotifications()` is definitely supported for our Pushy RN Android SDK, please make sure you are using the latest version in `build.gradle`.

Import version `1.0.14` of our React Native SDK by adding the following dependencies to your `android/app/build.gradle`, within the `dependencies {}` declaration:

```
// Pushy SDK for Android
compile 'me.pushy:sdk:1.0.54'

// Pushy SDK for React Native Android
compile 'me.pushy:sdk-react-native:1.0.14'
```

**Comment by jothikannan** [comment]
How we can do it in IOS?

**Comment by pushy-me** [comment]
Hi @jothikannan,
Great question. The best way to support temporarily disabling notifications for both platforms is by calling your own backend endpoint when users log out of your app, notifying your backend that the user has logged out, and possibly storing this as a boolean in your backend database.

Your backend can then check whether the user logged out (via the stored boolean) before sending a notification to that device through the [Send Notifications API](https://pushy.me/docs/api/send-notifications).

Please let me know if you need further clarification.
