### ISSUE TITLE
refresh a component on opening a notification

### ISSUE THREAD

**Issue by jothikannan** [pushy-me/pushy-react-native#41]
I need to refresh a component on opening the notification as I need to do a fetch action to update the list of data as I receive the notification about the new data has been added, I tried multiple ways but nothing is working. can you please tell me how we can achieve it? I am using react-navigation for the navigation I tried all the way to do the redirect to home screen another screen on `setNotificationClickListener` but not working

**Comment by pushy-me** [comment]
Hi @jothikannan,
We recommend using the Observer Pattern to communicate between components in React:
https://www.javascriptstuff.com/component-communication/#6-observer-pattern

Unfortunately implementation advice is out of the scope of Pushy support. Please consult Google/StackOverflow for further guidance.
