### ISSUE TITLE
'React/RCTBundleURLProvider.h' file not found

### ISSUE THREAD

**Issue by VitaliiK91** [pushy-me/pushy-react-native#43]
Hi there,
I am using react-native 0.61.5 and when I add `use_frameworks!` to the Podfile I am getting the build error `'React/RCTBundleURLProvider.h' file not found` in `AppDelegate.m`

**Comment by pushy-me** [comment]
Hi @VitaliiK91,
Unfortunately we can't reproduce.

Here's the commands we ran:

```
npm install -g react-native@latest
react-native init AwesomeProject
cd AwesomeProject/

npm install pushy-react-native --save
react-native link pushy-react-native

nano ios/Podfile # inserting use_frameworks! right below use_native_modules!

cd ios && pod install
open *.xcworkspace # and build & run the project (which succeeded)
```

Please make sure you add `use_frameworks!` right beneath `use_native_modules`.

**Comment by VitaliiK91** [comment]
Hi @pushy-me , I was able to build the iOS app after updated to the latest XCode project. Thanks!
