### ISSUE TITLE
Actionable notifications

### ISSUE THREAD

**Issue by VitaliiK91** [pushy-me/pushy-react-native#44]
Hi there,
Is there a way to create actionable notification (notifications that can be responded without launching the app with quick actions) as described [here](https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types#overview)? Thanks!

**Comment by pushy-me** [comment]
Hi @VitaliiK91,
For actionable notifications (iOS) on React Native, please follow this guide:
https://medium.com/@martco/triggering-ios-actionable-push-notifications-via-react-native-7990a6a3c3f4

You can then pass the `{mutable_content: true}` flag to our [Send Notifications API](https://pushy.me/docs/api/send-notifications) for your app's Notification Service Extension to be invoked.

**Comment by VitaliiK91** [comment]
@pushy-me Hi, this tutorial shows how to implement this feature using [push-notifications-ios](https://github.com/react-native-community/push-notification-ios) library, but I am not sure how to make it work with pushy. I tried to add notification service extension to the project but didReceive never get triggered. I am missing something? 
AppDelegate.h
```
#import <UIKit/UIKit.h>
#import "RNAppAuthAuthorizationFlowManager.h"
#import <UserNotifications/UNUserNotificationCenter.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate, RNAppAuthAuthorizationFlowManager, UNUserNotificationCenterDelegate>

@property(nonatomic, weak)id<RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;
@property (nonatomic, strong) UIWindow *window;

@end
```
AppDelegate.m
```
#import "AppDelegate.h"

// #import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>
#import <PushyModule.h>
#import <UserNotifications/UserNotifications.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
  
  // Initialize Pushy Module
  [PushyModule didFinishLaunchingWithOptions:launchOptions];
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  return YES;
}

//Called when a notification is delivered to a foreground app.
-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}

@end
```

NoticationViewController.swift
```
import UIKit
import UserNotifications
import UserNotificationsUI

class NotificationViewController: UIViewController, UNNotificationContentExtension {

    @IBOutlet var label: UILabel?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any required interface initialization here.
    }
    
    func didReceive(_ notification: UNNotification) {
        self.label?.text = notification.request.content.body
    }

}
```

**Comment by VitaliiK91** [comment]
Hi @pushy-me ,
I was able to show action buttons for my notification.
I realized I needed to register categories in AppDelegate.m
Here is my AppDelegate.m body:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
  
  // Initialize Pushy Module
  [PushyModule didFinishLaunchingWithOptions:launchOptions];
  
  // Create the custom actions
UNNotificationAction* alertsAction = [UNNotificationAction
        actionWithIdentifier:@"ALERTS_ACTION"
        title:@"Open Notifications"
        options:UNNotificationActionOptionForeground];
   
  UNNotificationAction* reportsAction = [UNNotificationAction
        actionWithIdentifier:@"REPORTS_ACTION"
        title:@"Open Reports"
        options:UNNotificationActionOptionForeground];
  
  UNNotificationCategory* generalCategory = [UNNotificationCategory
  categoryWithIdentifier:@"GENERAL"
  actions:@[alertsAction, reportsAction]
  intentIdentifiers:@[]
  options:UNNotificationCategoryOptionNone];
  
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  
  [center setNotificationCategories:[NSSet setWithObjects:generalCategory, nil]];

  return YES;
}
```
The problem I am facing now is that when action button is clicked the JS callback is not being called:
```
function notificationClickHandler(data) {
  console.log(data);
}
Pushy.setNotificationClickListener(notificationClickHandler)
```
It is however being called when I just click on notification (w/o using action buttons), any suggestions how I can make it work?
Just in case this is notification I send:
```
{
	"to": "f746fe3c8369cb20078869",
	"data": {
		 "message": "Hello World!"
	},
	"notification": {
		"body": "Hello World \u270c",
		"badge": 1,
		"sound": "ping.aiff",
		"category": "GENERAL"
	},
        "mutable_content": true
}
```
Thanks!

**Comment by VitaliiK91** [comment]
I did some debugging and noticed that when I just click on notification the following code in `Pushy.swift` in ios/SDK is called:
```
// Device received notification
    @objc public func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        // Call the notification handler, if defined
        Pushy.shared?.notificationHandler?(userInfo, completionHandler)
    }
```
But it isn't when I click on either of action buttons.

**Comment by pushy-me** [comment]
Hi @VitaliiK91,
Thanks for the further investigation. You've made some great progress so far.

To handle the action buttons from an Actionable Notification, you need to add another delegate in AppDelegate.m `userNotificationCenter(_:didReceive:withCompletionHandler:)`:
https://developer.apple.com/documentation/usernotifications/handling_notifications_and_notification-related_actions

The code on this page is in Swift and will need to be converted to Objective C.

You could also write some code in this delegate to send an event over the React Native bridge to execute your JS code when a notification action button is pressed, but we cannot provide further support on how to achieve this. Please consult the React Native docs if you are interested.

**Comment by VitaliiK91** [comment]
@pushy-me thanks for helping out. I forgot to mention I did implement the method in AppDelegate.m
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
           didReceiveNotificationResponse:(UNNotificationResponse *)response
           withCompletionHandler:(void (^)(void))completionHandler {

    if ([response.actionIdentifier isEqualToString:UNNotificationDismissActionIdentifier]) {
        // The user dismissed the notification without taking action.
    }
    else if ([response.actionIdentifier isEqualToString:UNNotificationDefaultActionIdentifier]) {
        // The user launched the app.
    }

    if ([response.notification.request.content.categoryIdentifier isEqualToString:@"GENERAL"]) {
        // Handle the actions
        if ([response.actionIdentifier isEqualToString:@"ALERTS_ACTION"])
        {

        }
        else if ([response.actionIdentifier isEqualToString:@"REPORTS_ACTION"])
        {
            
        }

    }
  completionHandler();
}
```
also I assigned center delegate to AppDelegate instance to be able to use it
```
// Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
```
however when delegate assigned to `self` it does not make it to Pushy.swift module and I loose callbacks even on simple notification push

**Comment by pushy-me** [comment]
Hi @VitaliiK91,
That's fixable by invoking the Pushy internal notification listener in your `userNotificationCenter(_:didReceive:withCompletionHandler:)` method:

```
        // Call internal Pushy SDK method
        self.pushy?.application(application, didReceiveRemoteNotification:response.notification fetchCompletionHandler: completionHandler)
```

Make sure to assign the `new Pushy()` instance you are creating in `didFinishLaunchingWithOptions` to `self` and declare the variable:

```
self.pushy = Pushy(UIApplication.shared)
```

**Comment by VitaliiK91** [comment]
Hi @pushy-me , I am trying to follow your advice and call pushy callback in userNotificationCenter method, however I noticed that completionHandler in method is of type `(void) -> void` vs expected type `(UIBackgroundFetchResult) -> Void` of pushy `application` callback
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
           didReceiveNotificationResponse:(UNNotificationResponse *)response
           withCompletionHandler:(void (^)(void))completionHandler {
[pushy application:[UIApplication sharedApplication] didReceiveRemoteNotification:[response notification] fetchCompletionHandler: **NOT_SURE_WHAT_GOES_HERE**];
}
```
This is how I initialize pushy in `didFinishLaunchingWithOptions`
```
pushy = [[Pushy alloc]init:[UIApplication sharedApplication]];
```

Not sure if I am missing something? Thank you!

**Comment by pushy-me** [comment]
Hi @VitaliiK91,
Please try passing in `nil` for `fetchCompletionHandler`.
