### ISSUE TITLE
Cant register Pushy when app loads

### ISSUE THREAD

**Issue by DanielDanaee** [pushy-me/pushy-react-native#45]
> "pushy-react-native": "^1.0.14",
> "react-native": "0.61.2",

I get the following message when im opening the app.

`Error: Registration failed: Error Domain=PushyRN.PushyResponseException Code=0 "(null)"
`

**Comment by pushy-me** [comment]
Hi @DanielDanaee,
Please make sure that you have created an app in the Pushy dashboard with the same Bundle ID as your React Native iOS project:
https://dashboard.pushy.me/apps/new

After creating a Pushy app, please try running your app again. 👍
