### ISSUE TITLE
Both Notification listener and Notificatin click listeners get called when i tap on notification

### ISSUE THREAD

**Issue by adnandev09** [pushy-me/pushy-react-native#47]
Hi there, 
i am navigating to a route in notification click listener
and showing an in-app notification in notification listener
but the issue i am having is both the notification listener and notification click listener are getting called and i want only click listener to be called if user is coming from clicking a notification.
Is there a way to handle this scenario that if i open the app by tapping on notification, only click listener gets called and not the notification listener?

**Comment by pushy-me** [comment]
Hi @adnandev09,
This is possible, but will require a slight change in the source for of the Pushy RN SDK.

In your Xcode project, go to **LIbraries** -> **PushyRN.xcodeproj** -> Edit `PushyModule.m`.

**Find:**

```
        // Emit RCT event with notification payload dictionary
        [self sendEventWithName:@"Notification" body:data];
        
        // Check if app was inactive (this means notification was clicked)
        if ([[UIApplication sharedApplication] applicationState] == UIApplicationStateInactive) {
            // Emit RCT notification click event with notification payload dictionary
            [self sendEventWithName:@"NotificationClick" body:data];
        }
```

Replace with:
```
        // Check if app was inactive (this means notification was clicked)
        if ([[UIApplication sharedApplication] applicationState] == UIApplicationStateInactive) {
            // Emit RCT notification click event with notification payload dictionary
            [self sendEventWithName:@"NotificationClick" body:data];
        }
        else {
            // Emit RCT event with notification payload dictionary
            [self sendEventWithName:@"Notification" body:data];
        }
```

Run your app and let us know if it works. 😄
