### ISSUE TITLE
Specify the iOS notification content in client side just like Android. 

### ISSUE THREAD

**Issue by tarikchakur** [pushy-me/pushy-react-native#5]
Hi. Sorry for opening an issue for the question but  I couldn't find an answer eslewhere.
I was wondering if there is a way to specify the notification content in iOS, in the client side just like in Android we use `Pushy.notify( notificationTitle, notificationText );`  to specify the title and the message on `Pushy.setNotificationListener` event received.
From the documentation it seems that the notification content can only be set from the **Sender** but not from the **Receiver** in **iOS**.

**Comment by pushy-me** [comment]
Hi @tarikchakur,
On iOS, notification content and appearance needs to be prepared on the server-side (unless using Notification Service Extension) but this is not recommended as APNs will throttle notifications more frequently than classic iOS notifications.

Sample iOS `notification` params:

```
{
    "to": "a6345d0278adc55d3474f5",
    "data": {
        "message": "Hello World!"
    },
    "notification": {
        "body": "Hello World \u270c",
        "badge": 1,
        "sound": "ping.aiff"
    }
}
```

More info in our Send Notifications API reference:
https://pushy.me/docs/api/send-notifications
