### ISSUE TITLE
Suport for RN >= 60?

### ISSUE THREAD

**Issue by kayzenkayzen** [pushy-me/pushy-react-native#52]
Does this sdk support RN >= 60? 
The example provided use RN.59, and the documentation shows that we need to run link command, Doe this library support autolinking?

Thanks!

**Comment by pushy-me** [comment]
Hi @kayzenkayzen,
We'd be glad to assist with your inquiry.

This package supports RN >= 60 through manual linking. Please follow the docs here:
https://pushy.me/docs/additional-platforms/react-native
