### ISSUE TITLE
Changing bundle id doesn't change device token

### ISSUE THREAD

**Issue by leongzwss** [pushy-me/pushy-react-native#55]
Changing the bundle id (from com.A to com.B) and creating new app in pushy dashboard doesn't make app subscribe to new app and get the respective token, the app on iphone is still bounded to app com.A instead of com.B

**Comment by pushy-me** [comment]
Hi @leongzwss,
The Pushy iOS SDK persists the device credentials in the `iOS Keychain` to recognize the device between app reinstalls, and in the `NSUserDefaults` as well.

Both of these storage mechanisms are Bundle-bound and reset when you change the iOS app's Bundle ID, which means calling `Pushy.register()` after changing the bundle ID should in fact generate a new device token on the device.

We cannot reproduce this issue on our development device.
