### ISSUE TITLE
Reconfigure didRegisterForRemoteNotificationsWithDeviceToken on React Native iOS (Objective-C)

### ISSUE THREAD

**Issue by XfortunaX** [pushy-me/pushy-react-native#57]
Good day,
Can you tell me how this config will look like in React Native in the AppDelegate.m (Objective-C) file?

_Originally posted by @XfortunaX in https://github.com/pushy-me/pushy-react-native/issues/56#issuecomment-741705820_

**Comment by pushy-me** [comment]
Hi @XfortunaX,
Please see our response in https://github.com/pushy-me/pushy-react-native/issues/56#issuecomment-741841445.
