### ISSUE TITLE
Push notifications do not come to iOS when the phone is in sleep mode

### ISSUE THREAD

**Issue by XfortunaX** [pushy-me/pushy-react-native#58]
Hello,
Push notifications do not come to iOS when the phone is in sleep mode. Can you do something about it?

*Params content_available set true.

**Comment by pushy-me** [comment]
Hi @XfortunaX,
We'd be glad to assist.

If your app has been swiped away from the recent apps (force closed) on iOS, silent notifications (using `content_available: true`) will not wake up your app until the user manually re-opens your app by clicking its icon in the Springboard.

This is an Apple platform restriction. We apologize for the inconvenience.
