### ISSUE TITLE
Red Screen shows up on iOS when notification is received while the app is in foreground

### ISSUE THREAD

**Issue by leoskyrocker** [pushy-me/pushy-react-native#6]
#### Steps to Reproduce
1) Open your app.
2) Send a notification from the Pushy UI

#### Expected
A notification is received without errors

#### Actual
Red screen appears
![img_0277](https://user-images.githubusercontent.com/2366893/47766379-47921400-dd09-11e8-8bad-9bae6575dd15.PNG)

**Comment by pushy-me** [comment]
Hi @leoskyrocker,
Merged! Thanks so much for reporting this issue and submitting this PR! 💯 

Released in `1.0.4`:
```
npm install pushy-react-native@1.0.4 --save
```
