### ISSUE TITLE
No device token on iOS

### ISSUE THREAD

**Issue by Vaintti** [pushy-me/pushy-react-native#62]
When I register Pushy it doesn't give device token on iOS. Works fine on Android

**Comment by pushy-me** [comment]
Hi @Vaintti,
Thanks for reaching out. We'd be glad to assist with your inquiry.

Please consult this article for a solution:
[iOS: Pushy.register() callback not invoked](https://support.pushy.me/hc/en-us/articles/360043565872)

Please let me know if there's anything else we can help with.

**Comment by Vaintti** [comment]
The app doesn't override any of those methods mentioned in the article. Pushy.register() results to a callback but doesn't return token. How can we fix this?

**Comment by pushy-me** [comment]
@Vaintti Is the `.catch()` block being executed with an error message?


Please use the following sample code to test `Pushy.register()`, and check the logcat for any errors:

```
// Register the user for push notifications
Pushy.register().then(async (deviceToken) => {
    // Display an alert with device token
    alert('Pushy device token: ' + deviceToken);

    // Send the token to your backend server via an HTTP GET request
    //await fetch('https://your.api.hostname/register/device?token=' + deviceToken);

    // Succeeded, optionally do something to alert the user
}).catch((err) => {
    // Handle registration errors
    console.error(err);

   // Alert with error
   alert(err.toString());
});
```

**Comment by Vaintti** [comment]
Nope. The catch block is not executed but then block is (with no device token)

**Comment by pushy-me** [comment]
Hi @Vaintti,
This is really strange, we've never received reports of such behavior before.

1) If you `console.log()` the `deviceToken`, is it `null` or `undefined` or an empty string `''`?

2) Can you please paste your `package.json` contents, or at least just the `dependencies` section?

Thanks for your help!

**Comment by Vaintti** [comment]
It returns empty string.

Here's my dependencies
``` json
{
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.2.3",
    "@react-native-firebase/app": "^10.8.1",
    "@react-native-firebase/crashlytics": "^10.8.1",
    "axios": "^0.21.1",
    "hoist-non-react-statics": "^3.3.2",
    "intl": "^1.2.5",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "pushy-react-native": "^1.0.17",
    "qs": "^6.9.6",
    "react": "17.0.1",
    "react-native": "^0.63.4",
    "react-native-collapsible": "^1.5.3",
    "react-native-datepicker": "^1.7.2",
    "react-native-document-picker": "^5.0.0",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-google-places-autocomplete": "^2.1.3",
    "react-native-image-picker": "2.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-keyboard-manager": "4.0.13-17",
    "react-native-keychain": "6.2.0",
    "react-native-localization": "^2.1.6",
    "react-native-maps": "^0.27.1",
    "react-native-modal": "^11.6.1",
    "react-native-modal-dropdown": "https://github.com/siemiatj/react-native-modal-dropdown",
    "react-native-parsed-text": "^0.0.22",
    "react-native-pdf": "^6.2.2",
    "react-native-reanimated": "^1.13.2",
    "react-native-render-html": "^5.0.1",
    "react-native-restart": "^0.0.20",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "^2.17.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-icon": "^0.9.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-vector-icons": "^8.0.0",
    "react-native-version-check": "^3.4.2",
    "react-native-webview": "^11.2.1",
    "react-navigation": "^4.4.3",
    "react-navigation-drawer": "^2.7.0",
    "react-navigation-stack": "^2.10.2",
    "react-navigation-tabs": "^2.10.1",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.4",
    "redux-axios-middleware": "^4.0.0",
    "redux-persist": "5.10.0",
    "redux-persist-filesystem-storage": "3.0.0",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "0.12.0",
    "validator": "^13.5.2"
  }
```

**Comment by pushy-me** [comment]
@Vaintti Thanks for sending over the dependencies.

Indeed, we've never seen this behavior before, with an empty string being returned.

Is there any way we can ask you to share your project files securely with us via e-mail, so we can try to reproduce and resolve the issue? If so, please send a download link over to support@pushy.me.

**Comment by Vaintti** [comment]
I cannot share the project files. Any other way to solve the issue or things I could try?

**Comment by pushy-me** [comment]
Hi @Vaintti,
1) In your own project, please open the `Info.plist` file, and add a new `BOOLEAN` flag called `FirebaseAppDelegateProxyEnabled` with its value set to `NO`. Please run your app after making this change, and observe whether the device token is still an empty string.

2) If it's still an empty string, can you please try to reproduce this issue on the same device by running the Pushy RN Demo App on your iOS device?
https://github.com/pushy-me/pushy-demo-react-native#get-started

Is a device token displayed in the demo app?

3) If you can't share your entire app, how about just the contents of the `AppDelegate.m` file? 

4) This might seem silly, but please ensure that In your own project, the `Push Notifications` capability is enabled in the Project editor:
![https://pushy.me/img/docs/enable-push-notifications.png](https://pushy.me/img/docs/enable-push-notifications.png)

Thanks for your assistance in debugging this further!

**Comment by Vaintti** [comment]
Push notification capability is set. I tried FirebaseAppDelegateProxyEnabled flag set to NO

Metro bundler crashes when I try to build the test project

```
pushy-demo-react-native/node_modules/graceful-fs/polyfills.js:285
        if (cb) cb.apply(this, arguments)
                   ^

TypeError: cb.apply is not a function
```

AppDelegate.m
``` objective-c
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "../../node_modules/pushy-react-native/ios/PushyModule.h"
#import <GoogleMaps/GoogleMaps.h>
#import "RNSplashScreen.h"
#import <Firebase.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // Fix iOS 14 issue with DatePicker component
  if (@available(iOS 14, *)) {
    UIDatePicker *picker = [UIDatePicker appearance];
    picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
  }
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  [[FBSDKApplicationDelegate sharedInstance] application:application
                             didFinishLaunchingWithOptions:launchOptions];
  // Initialize Pushy Module
  [PushyModule didFinishLaunchingWithOptions:launchOptions];

  [GMSServices provideAPIKey:@"[API_KEY]"];

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"[Module Name]"
                                            initialProperties:nil];


  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [RNSplashScreen showSplash:@"LaunchScreen" inRootView:rootView];
  
  return YES;
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(nonnull NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options
{
  [[FBSDKApplicationDelegate sharedInstance] application:application
                                                 openURL:url
                                                 options:options];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

**Comment by pushy-me** [comment]
Hi @Vaintti,
Can you please try running your app with the following lines of code temporarily removed from `AppDelegate.m`?

```
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
```

**Comment by Vaintti** [comment]
No luck with disabling firebase either.

**Comment by pushy-me** [comment]
Hi @Vaintti,
We're really sorry, but to continue with the investigation, we will need you to send over your project files so we can try to reproduce the issue locally. Since the issue isn't happening with a clean integration of the Pushy React Native SDK in a new project, nor in the [pushy-demo-react-native](https://github.com/pushy-me/pushy-demo-react-native) project, the issue must lie inside your own project configuration, source code, or included dependencies.

If you could send over your project files securely and confidentially, please send them via e-mail. Thanks for your help in continuing investigation, and apologies for the inconvenience.

**Comment by Vaintti** [comment]
I managed to find out what caused it. Apparently having letter "ä" in "Build Settings -> Packaging -> Product Name" breaks push notifications on newer iOS versions

**Comment by pushy-me** [comment]
Hi @Vaintti,
Glad to hear it, thanks for keeping us posted. Indeed the only way for us to have figured that out is by having access to the project files. 

Cheers! 😄

**Comment by 4sskick** [comment]
> I managed to find out what caused it. Apparently having letter "ä" in "Build Settings -> Packaging -> Product Name" breaks push notifications on newer iOS versions

where can I see that? I have same issue on iOS version 17.4.1 but mine is not invoke the `catch` and `then` block. Already saw [iOS: Pushy.register() callback not invoked](https://support.pushy.me/hc/en-us/articles/360043565872). @pushy  The project also have FCM & HCM also override the methods

`application:didRegisterForRemoteNotificationsWithDeviceToken`
`application:didFailToRegisterForRemoteNotificationsWithError`
`application:didReceiveRemoteNotification:fetchCompletionHandler`

**my AppDelegate.m**
![image](https://github.com/pushy/pushy-react-native/assets/7526887/73c00881-47f1-4e9d-849b-cdcc0253517d)

**my RN implementation**
![image](https://github.com/pushy/pushy-react-native/assets/7526887/c7e8d45a-c5ff-4d56-bb0d-06c893dafea3)

**Comment by pushy** [comment]
Hi @4sskick,
Thanks for reaching out. We'd be glad to assist.

Since you are using FCM, please ensure you have **disabled method swizzling** in the FCM SDK as well as the Pushy SDK. For Firebase, please follow the instructions mentioned in the [official Firebase docs](https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in). This involves setting the `FirebaseAppDelegateProxyEnabled` flag to `NO` in the app's `Info.plist`.

Also, please make sure to disable the Pushy iOS SDK method swizzling by calling `Pushy.toggleMethodSwizzling(false)` in `App.js` before `Pushy.listen()`:

```
// Disable AppDelegate method swizzling
Pushy.toggleMethodSwizzling(false);
```

For the SDK to continue working properly after disabling method swizzling, please override the following APNs methods in your `ios/AppDelegate.m` implementation file, making sure to invoke the Pushy iOS SDK at the end of each of them, by adding the following APNs method overrides:

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [[PushyModule getSharedPushyInstance] application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [[PushyModule getSharedPushyInstance] application:application didFailToRegisterForRemoteNotificationsWithError:error];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
  [[PushyModule getSharedPushyInstance] application:application didReceiveRemoteNotification:userInfo];
}

- (void) application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  [[PushyModule getSharedPushyInstance] application:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
```

For the FCM SDK to continue to function, you'll need to explicitly map your APNs token to the FCM registration token by adding the following line of code inside  `didRegisterForRemoteNotificationsWithDeviceToken`:

```
Messaging.messaging().apnsToken = deviceToken
```

Please give it a try, and let us know if you face any issues.
