### ISSUE TITLE
Support for toggling in-app notification banner

### ISSUE THREAD

**Issue by irbisdev** [pushy-me/pushy-react-native#67]
Can you add support for toggling in-app notification banner like in [pushy-sdk-ios](https://github.com/pushy-me/pushy-sdk-ios/blob/master/PushySDK/Pushy.swift#L501)?

**Comment by pushy-me** [comment]
Hi @irbisdev,
Thanks so much for your patience. 

We've just released version `1.0.20` of the Pushy RN SDK which adds support for `Pushy.toggleInAppBanner()`.

Run the following commands in the root directory of your project to update to the latest `pushy-react-native` package from `npm` and relink the iOS module:

```
npx react-native unlink pushy-react-native
npm install pushy-react-native@1.0.20 --save
npx react-native link pushy-react-native
```

Then, call `Pushy.toggleInAppBanner(true)` in `App.js` before `Pushy.setNotificationListener()`:

```
// Enable in-app notification banners (iOS 10+)
Pushy.toggleInAppBanner(true);
```

Please let us know if you face any issues.
