### ISSUE TITLE
    Pushy native module not loaded, please make sure to run "react-native link pushy-react-native" to link the native library to your project.

### ISSUE THREAD

**Issue by sohamad** [pushy-me/pushy-react-native#71]
I have already ran link command and got this message 
info iOS module "pushy-react-native" is already linked. How do i resolve this issue.

**Comment by pushy-me** [comment]
Hi @sohamad,
We'd be glad to assist.

If you're getting an error that the `pushy-react-native` module is already linked, then you do not need to run the `react-native link pushy-react-native` command again. The module is already linked and nothing else needs to be done.

Please let us know if you face any other issues that we can assist with.

**Comment by sohamad** [comment]
When i start building i get this error even if pushy is linked Pushy native module not loaded, please make sure to run "react-native link pushy-react-native" to link the native library to your project.

**Comment by sohamad** [comment]
this is resolved now
