### ISSUE TITLE
build/Release-iphoneos/PushyRN/PushyRN.modulemap' not found 1 error generated.

### ISSUE THREAD

**Issue by sohamad** [pushy-me/pushy-react-native#72]
As soon as i add pushy react native to package.json i get the above error. How do i resolve this.

**Comment by pushy-me** [comment]
Hi @sohamad,
We'd be glad to assist.

Please do not manually add `pushy-react-native` to your project's `package.json`. The necessary steps for installing our React Native SDK are as follows:

Run the following command in the root directory of your project to install the [pushy-react-native](https://www.npmjs.com/package/pushy-react-native) package from npm:

```
npm install pushy-react-native --save
```

Run the following command to link the ios native module to your project:

```
react-native link pushy-react-native
```

Run the following command to install the PushyRN Cocoapods dependency:
```
cd ios && pod install
```

Finally, please close all open Xcode projects and make sure to reopen your RN project using the new `*.xcworkspace` file by running this command:

```
open *.xcworkspace
```
Rebuild your project, and it should build successfully this time.

Please let us know if you face any other issues that we can assist with.

**Comment by sohamad** [comment]
I haven't added it manually i have only added it with npm install only.

**Comment by sohamad** [comment]
I have added Pushy.swift file as well nothing seems to be working i am blocked at this point.

**Comment by pushy-me** [comment]
Hi @sohamad,
Let's continue discussions in the new issue you created (#73).
