### ISSUE TITLE
Enable pushy for android only

### ISSUE THREAD

**Issue by sohamad** [pushy-me/pushy-react-native#73]
I am getting errors in ios build so is there a way i can disable pushy from getting autolinked to ios. Since i am targeting android only as of now and pushy is working fine in android.

**Comment by sohamad** [comment]
Any solution for this?

**Comment by pushy-me** [comment]
Hi @sohamad,
Please follow these steps to unlink the Pushy RN SDK from your iOS project:

1) Run the following command to unlink the `ios` native module from your project:

```
react-native unlink pushy-react-native
```

2) Edit the `ios/Podfile` file, remove any lines mentioning `Pushy`, and save the file.

3) Run the following command to uninstall the Cocoapods dependency:
```
cd ios && rm -rf Podfile.lock && pod install
```

4) Remove these two lines of code from your `ios/app/AppDelegate.m` file:

```
#import <PushyModule.h>
[PushyModule didFinishLaunchingWithOptions:launchOptions];
```

5) Rebuild your project and check whether the build error is resolved. If not, please copy and paste the exact build error so we can debug further.

**Comment by pushy-me** [comment]
Closing the issue due to lack of response, feel free to reply if you still need help with this.
