### ISSUE TITLE
Unable to react-native link pushy-react-native

### ISSUE THREAD

**Issue by chankahmun** [pushy-me/pushy-react-native#74]
Hi, I follow this doc to integrate with pushy push notification service. (https://pushy.me/docs/additional-platforms/react-native). When I come to IOS and trying link the push-react-native, issue below happens. Anyone know how to fix this issue or there is alternative way?? 

Issue
*--------
info Linking "pushy-react-native" iOS dependency
error Linking "pushy-react-native" failed. Run CLI with --verbose flag for more details.

![image](https://user-images.githubusercontent.com/45312550/165008783-be7a0107-15c4-4c41-a2eb-d66dc9584751.png)

Thanks in advanced

**Comment by pushy-me** [comment]
Hi @chankahmun,
We'd be glad to assist.

Please run the command with the `--verbose` flag as follows and send a screenshot of the detailed error:

```
react-native link pushy-react-native --verbose
```

**Comment by chankahmun** [comment]
Hi @pushy-me 

![image](https://user-images.githubusercontent.com/45312550/165045265-0a378f3e-0952-411b-8502-2fa72d5c9dca.png)

**Comment by chankahmun** [comment]
Sorry, this is the last line. There was no more line after "error Linking "pushy-react-native" failed.

I tried to add below code directly into Podfile and "cd ios & pod install". It fixed my problem.

![image](https://user-images.githubusercontent.com/45312550/165203165-cefc4f9a-9d14-473d-aed3-fd5a9dfb9ca8.png)

**Comment by pushy-me** [comment]
Hi @chankahmun,
Glad to hear you were able to resolve the issue! 👍
