### ISSUE TITLE
Notification when app is terminated

### ISSUE THREAD

**Issue by lukecyca** [pushy-me/pushy-react-native#8]
I've switched to Pushy after struggling to get reliable heads-up notifications through FCM in all app states on Android (foreground, background, terminated).

I've set up Pushy and it works very well in foreground and background. However when the app is terminated, the notification is not received at all in any form. Is this expected behaviour or am I missing something? Even if heads-up notification is not possible in the terminated state, I need it to fallback to _some_ type of notification.

My test environment is:
- Platform: Android
- Phone: Samsung Galaxy A5
- react-native: 0.57.4
- pushy-react-native: 1.0.4

Thanks!

**Comment by pushy-me** [comment]
Hi @lukecyca,
Thanks so much for your inquiry.

By terminated, do you mean Force Closed? In that case, this is expected behavior, as no app on Android can display notifications on run any code after being Force Closed. Or are you referring to being swiped away from the recent apps list?

**Comment by lukecyca** [comment]
I'm just trying to understand under what circumstances notifications would not be received by a user.

My exact steps are:

1. Run my app in development mode (`react-native run-android`) on my Samsung Galaxy A5
2. My app registers with Pushy and shows up in "Recent Devices" in the Pushy console
3. I use the Pushy console to send a test notification while the app is in the foreground, and it shows up in a heads-up bubble at the top of the screen. Good!
4. I click the physical home button on the device, and the app disappears to the background. I send another test notification from the console, and it show up in the same kind of heads-up bubble. Good!
5. I click the physical "Recents" button on the device, bringing up a list of recent apps. I swipe my app out of this list so it goes away. I press the home button again. I send another test notification. The console says it was sent successfully but nothing happens on the phone (no heads-up bubble, and nothing appears in the notification tray). Bad!
6. I reboot the phone and send another notification. Nothing happens. Bad!

I guess my questions are:
* Should the device get notifications in scenario 5 (app swiped out of recents) and scenario 6 (cold boot)?
* If not, is there any way to achieve this (possibly in combination with FCM)?

Thanks for your help!

UPDATE: While doing the testing above, I received the following possibly-related exception via Sentry.io, I think while starting my app:

```
Error: No task registered for key PushyPushReceiver
  at startHeadlessTask(app:///index.delta:65169:24)
  at __callFunction(app:///index.delta:2464:49)
  at ? (app:///index.delta:2237:31)
  at __guard(app:///index.delta:2418:15)
  at callFunctionReturnFlushedQueue(app:///index.delta:2236:21)
  at [native code] callFunctionReturnFlushedQueue(:0:0)
```

**Comment by lukecyca** [comment]
I ran the app from within Android Studio. The app successfully registers, but crashes when a notification is received:

```
D/Pushy: Received push for package com.example.app
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 18899
    java.lang.RuntimeException: Unable to instantiate receiver com.example.app.PushReceiver: java.lang.ClassNotFoundException: Didn't find class "com.example.app.PushReceiver" on path: DexPathList[[zip file "/data/app/com.example.app--pwMDpMYfqhLXdV6ER1SCw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app--pwMDpMYfqhLXdV6ER1SCw==/lib/arm, /data/app/com.example.app--pwMDpMYfqhLXdV6ER1SCw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3376)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.app.PushReceiver" on path: DexPathList[[zip file "/data/app/com.example.app--pwMDpMYfqhLXdV6ER1SCw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app--pwMDpMYfqhLXdV6ER1SCw==/lib/arm, /data/app/com.example.app--pwMDpMYfqhLXdV6ER1SCw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3371)
        at android.app.ActivityThread.-wrap18(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

Here are my gradle deps:
```
dependencies {
    compile project(':react-native-sentry')
    compile project(':react-native-splash-screen')
    compile project(':react-native-cookies')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:27.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules

    // Pushy SDK for Android
    compile 'me.pushy:sdk:1.0.42'

    // Pushy SDK for React Native Android
    compile 'me.pushy:sdk-react-native:1.0.6'
}
```

And my AndroidManifest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.app">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />

    <application
        android:name=".MainApplication"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">

        <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:label="@string/app_name"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

        <!-- Pushy Declarations -->

        <!-- Pushy Notification Receiver -->
        <!-- Incoming push notifications will invoke the following BroadcastReceiver -->
        <receiver android:name=".PushReceiver" android:exported="false">
            <intent-filter>
                <!-- Do not modify this -->
                <action android:name="pushy.me" />
            </intent-filter>
        </receiver>

        <!-- Pushy Update Receiver -->
        <!-- Do not modify - internal BroadcastReceiver that restarts the listener service -->
        <receiver android:name="me.pushy.sdk.receivers.PushyUpdateReceiver" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>

        <!-- Pushy Boot Receiver -->
        <!-- Do not modify - internal BroadcastReceiver that restarts the listener service -->
        <receiver android:name="me.pushy.sdk.receivers.PushyBootReceiver" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>

        <!-- Pushy Socket Service -->
        <!-- Do not modify - internal service -->
        <service android:name="me.pushy.sdk.services.PushySocketService"/>

        <!-- Pushy Job Service (added in Pushy SDK 1.0.35) -->
        <!-- Do not modify - internal service -->
        <service android:name="me.pushy.sdk.services.PushyJobService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="true" />

        <!-- End Pushy Declarations -->
    </application>

</manifest>
```

I believe I have followed the [react native instructions](https://pushy.me/docs/additional-platforms/react-native) to a tee.

I did notice that in the plain android settings there is a step to [set up broadcast receiver](https://pushy.me/docs/android/setup-broadcastreceiver) which I have NOT done. Do I need to do this as well, or does `me.pushy:sdk-react-native` take care of this?

**Comment by pushy-me** [comment]
Hi @lukecyca,
It appears your `AndroidManifest.xml` declarations are incorrect (you are using the native Android declarations and not the [React Native declarations](https://pushy.me/docs/additional-platforms/react-native) in the docs). Specifically, the `<!-- Pushy Notification Receiver -->` is incorrect. This is the reason for the `ClassNotFoundException` you are receiving.

Please replace the `<!-- Pushy Declarations -->` section with the following:

```
<!-- Pushy Declarations -->

<!-- Pushy Notification Receiver -->
<!-- Do not modify - internal BroadcastReceiver that forwards notifications to the internal notification service-->
<receiver android:name="me.pushy.sdk.react.receivers.PushReceiver" android:exported="false">
    <intent-filter>
        <!-- Do not modify this -->
        <action android:name="pushy.me" />
    </intent-filter>
</receiver>

<!-- Pushy Update Receiver -->
<!-- Do not modify - internal BroadcastReceiver that restarts the listener service -->
<receiver android:name="me.pushy.sdk.receivers.PushyUpdateReceiver" android:exported="false">
    <intent-filter>
        <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
    </intent-filter>
</receiver>

<!-- Pushy Boot Receiver -->
<!-- Do not modify - internal BroadcastReceiver that restarts the listener service -->
<receiver android:name="me.pushy.sdk.receivers.PushyBootReceiver" android:exported="false">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"/>
    </intent-filter>
</receiver>

<!-- Pushy Socket Service -->
<!-- Do not modify - internal service -->
<service android:name="me.pushy.sdk.services.PushySocketService"/>

<!-- Pushy Job Service (added in Pushy SDK 1.0.35) -->
<!-- Do not modify - internal service -->
<service android:name="me.pushy.sdk.services.PushyJobService"
    android:permission="android.permission.BIND_JOB_SERVICE"
    android:exported="true" />

<!-- End Pushy Declarations -->
```

**Comment by pushy-me** [comment]
As per your previous question, your app should get notifications after swiped out of recents or after booting (within 5 seconds after being swiped away / within 30 seconds after phone boot), except for some Chinese market phones that will prevent your app from running code after being swiped away. What is your device manufacturer, model, and Android OS version?

Read more about possible delays here:
https://pushy.me/support#delays

**Comment by lukecyca** [comment]
I had previously been using the correct AndroidManifest.xml, but I guess I changed it to the wrong one recently during my attempts to explore solutions.

After switching back to the correct AndroidManifest.xml, that crash no longer occurs. However, I only get notifications while the app is running. Specifically:

* Sent when app in foreground: works
* Sent when app in background: works
* Closed app by opening recent apps and swiping my app out, then sent: not received
* Rebooted phone, then sent: not received.

Test device:
* Phone: Samsung Galaxy A5 (2017) SM-A520W
* Android: 8.0.0

**Comment by lukecyca** [comment]
I finally solved this by instrumenting react native's `registerHeadlessTask` and `startHeadlessTask` and noticing that my headless task was disappearing when I swiped my app out of recent applications, and not available to `startHeadlessTask` when a notification came in.

Root cause was that I was calling `Pushy.setNotificationListener()` from deep within a component's lifecycle (once my user is logged in, gives push notification permissions, etc.).

By moving Pushy.setNotificationListener() to `index.js`, the handler is available as a headless task as well.

Now I see this is prominently included in the docs:

>This method can only be called once for your entire app lifecycle, therefore, it should not be invoked within a Component lifecycle event.

**Comment by pushy-me** [comment]
Thanks for letting us know the underlying cause of the issue. We will investigate whether the React Native documentation can be changed to make this instruction more clear.

**Comment by callmejm** [comment]
@lukecyca Hi, so how actually received notification when app is terminated ?

**Comment by callmejm** [comment]
@pushy-me thank a lot

**Comment by iampapagray** [comment]
@pushy-me I have my Manifest looking exactly like mentioned above. I'm also calling Pushy.setNotificationListener() within my App.js file before my component class. However, I still only receive the notification when the app is in the foreground and when it is in the background. When the app is swiped off the recent apps, the notification is not received. 
"react-native": "0.61.5"
"pushy-react-native": "^1.0.14"


<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.myapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

                                   
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    

    <application
    android:usesCleartextTraffic="true"
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      

      

      
      
      <receiver android:name="me.pushy.sdk.react.receivers.PushReceiver" android:exported="false">
          <intent-filter>
              
              <action android:name="pushy.me" />
          </intent-filter>
      </receiver>

      
      
      <receiver android:name="me.pushy.sdk.receivers.PushyUpdateReceiver" android:exported="false">
          <intent-filter>
              <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
          </intent-filter>
      </receiver>

      
      
      <receiver android:name="me.pushy.sdk.receivers.PushyBootReceiver" android:exported="false">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED"/>
          </intent-filter>
      </receiver>

      
      
      <service android:name="me.pushy.sdk.services.PushySocketService" android:stopWithTask="false" />

      
      
      <service android:name="me.pushy.sdk.services.PushyJobService"
          android:permission="android.permission.BIND_JOB_SERVICE"
          android:exported="true"
           />
          

      

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustPan"
        android:exported="true">
        
      </activity>

      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/BootTheme"> 
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>


/
Pushy.setNotificationListener(async (data) => {
  // Print notification payload data
  console.log("Received notification: " + JSON.stringify(data));

  // Notification title
  let notificationTitle = data.title;
  let notificationText = data.message || "Test notification";

  // Display basic system notification
  Pushy.notify(notificationTitle, notificationText, data);
});


Please help...

**Comment by pushy-me** [comment]
@iampapagray Please check our response in #49.

**Comment by tryhardest** [comment]
If it is the case that on force close notifications cannot be delivered on Android, how are notifications delivered when a device is booted up but the app has not yet been opened... especially if the app has an essentral communication use like messaging and a msg is sent but user hasn't yet 'opened' app? @pushy-me if there is a socket how would it be established?

**Comment by pushy-me** [comment]
Hi @tryhardest,
The Pushy Android SDK listens to the `android.intent.action.BOOT_COMPLETED` intent broadcast and starts the socket service (JobScheduler) from there. 

However, a "Force Closed" app (by clicking the Force Close button in App Info) will never be able to run any kind of code again, until the user taps its icon once again. This is an Android platform implementation decision and cannot be worked around.
